#!/bin/sh

#Add all directories to ~/.local/bin to $PATH
export PATH="$PATH:$(find ~/.local/bin -type d | paste -sd ':' -)"

#Dissable Prompt
unsetopt PROMPT_SP 2>/dev/null

#Default programs
export EDITOR="nvim"
export TERMINAL="st"
export TERMINAL_PROG="st"
export BROWSER="librewolf"

#Home cleanup
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DOWNLOAD_DIR="$HOME/Downloads"
export XDG_DOCUMENTS_DIR="$HOME/Documents"
export XDG_MEDIA_DIR="$HOME/Media"
export XDG_PICTURES_DIR="$HOME/Pictures"
export XINITRC="$XDG_CONFIG_HOME/x11/xinitrc"
export HISTFILE="$XDG_DATA_HOME/history"

#Failsafe for shortcut
[ ! -f "$XDG_CONFIG_HOME/shell/shortcutrc" ] && setsid -f shortcuts >/dev/null 2>&1

#Start graphical server in tty if not already started
[ "$(tty)" = "/dev/tty1" ] && ! pidof -s Xorg >/dev/null 2>&1 && exec startx "XINITRC"

#Switch escape and caps on initial startup
sudo -n loadkeys "$XDG_DATA_HOME/scripts/ttymaps.kmap" 2>/dev/null
