#!/bin/sh

# Display
xrandr --dpi 96
setbg &

# Autostart
pgrep picom || picom &
pgrep dwmblocks || dwmblocks &
pgrep unclutter || unclutter &

# Keyboard
setxkbmap -option caps:swapescape

# Xresources
xrdb "$HOME/.Xresources"
